#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

#setxkbmap -layout us,ru
#setxkbmap -option 'grp:shift_toggle'

# userresources=$HOME/.Xresources
# usermodmap=$HOME/.Xmodmap
# sysresources=/etc/X11/xinit/.Xresources
# sysmodmap=/etc/X11/xinit/.Xmodmap

# DEFAULT_SESSION=startkde

# # merge in defaults and keymaps

# if [ -f $sysresources ]; then
#     xrdb -merge $sysresources
# fi

# if [ -f $sysmodmap ]; then
#     xmodmap $sysmodmap
# fi

# if [ -f "$userresources" ]; then
#     xrdb -merge "$userresources"
# fi

# if [ -f "$usermodmap" ]; then
#     xmodmap "$usermodmap"
# fi

# # start some nice programs

# if [ -d /etc/X11/xinit/xinitrc.d ] ; then
#     for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
#         [ -x "$f" ] && . "$f"
#     done
#     unset f
# fi

get_session(){
	local dbus_args=(--sh-syntax --exit-with-session)
	case $1 in
		i3|i3wm) dbus_args+=(i3 --shmlog-size 0) ;;
		#kde) dbus_args+=(startkde) ;;
	esac

	echo "dbus-launch ${dbus_args[*]}"
}

exec $(get_session)
xset r rate 600 25

