# Mankind was born on earth. it was never meant to die here.

export PATH=$HOME/bin:/usr/local/bin:$PATH
export SSH_KEY_PATH="~/.ssh/rsa_id"
export ZSH=/home/crime/.oh-my-zsh
export ARCHFLAGS="-arch x86_64"
export LANG=en_US.UTF-8
export EDITOR='vim'
export TERM='xterm'

# CUSTOM DIRECTORY PATH #
Deploy=$HOME/Coding/Deployment
Django=$HOME/Coding/Django

######### GO LANG ################
export GOPATH=$HOME/Coding/Go
export GOBIN=$GOPATH/bin
export GOPHER=$GOPATH/src/GoBook

ZSH_THEME="kardan"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

plugins=(git python django)
source $ZSH/oh-my-zsh.sh

alias pacs="sudo pacman -S"
alias pacs-sync="sudo pacman -Syu"
alias offline="systemctl poweroff"
alias nmli="nmcli dev wifi"

# Secret key for django
export s_key='lx2n9+j=saw&7h_g(-pg==-e06*&@&qpc!l!nuc781o091s&hc'
